# Constants for key codes in the project
PWE_NO_ERROR = 0
PWE_ERROR = 0b0001
PWE_RELEASE = 0
PWE_PRESS = 1

# ASCII values for common keys
PWE_KEY_SPACE = 32
PWE_KEY_APOSTROPHE = 39
PWE_KEY_COMMA = 44
PWE_KEY_MINUS = 45
PWE_KEY_PERIOD = 46
PWE_KEY_SLASH = 47
PWE_KEY_0 = 48
PWE_KEY_1 = 49
PWE_KEY_2 = 50
PWE_KEY_3 = 51
PWE_KEY_4 = 52
PWE_KEY_5 = 53
PWE_KEY_6 = 54
PWE_KEY_7 = 55
PWE_KEY_8 = 56
PWE_KEY_9 = 57
PWE_KEY_SEMICOLON = 59
PWE_KEY_EQUAL = 61
PWE_KEY_A = 65
PWE_KEY_B = 66
PWE_KEY_C = 67
PWE_KEY_D = 68
PWE_KEY_E = 69
PWE_KEY_F = 70
PWE_KEY_G = 71
PWE_KEY_H = 72
PWE_KEY_I = 73
PWE_KEY_J = 74
PWE_KEY_K = 75
PWE_KEY_L = 76
PWE_KEY_M = 77
PWE_KEY_N = 78
PWE_KEY_O = 79
PWE_KEY_P = 80
PWE_KEY_Q = 81
PWE_KEY_R = 82
PWE_KEY_S = 83
PWE_KEY_T = 84
PWE_KEY_U = 85
PWE_KEY_V = 86
PWE_KEY_W = 87
PWE_KEY_X = 88
PWE_KEY_Y = 89
PWE_KEY_Z = 90
PWE_KEY_LEFT_BRACKET = 91
PWE_KEY_BACKSLASH = 92
PWE_KEY_RIGHT_BRACKET = 93
PWE_KEY_GRAVE_ACCENT = 96
PWE_KEY_WORLD_1 = 161
PWE_KEY_WORLD_2 = 162

# Mouse button 
PWE_MOUSE_BUTTON_RIGHT = 0
PWE_MOUSE_BUTTON_LEFT = 1
PWE_MOUSE_BUTTON_MIDDLE = 2

# ASCII values for special keys
PWE_KEY_BACKSPACE = 8
PWE_KEY_TAB = 9
PWE_KEY_ENTER = 13
PWE_KEY_SHIFT = 16
PWE_KEY_CONTROL = 17
PWE_KEY_ALT = 18
PWE_KEY_CAPS_LOCK = 20
PWE_KEY_ESC = 27
PWE_KEY_PAGE_UP = 33
PWE_KEY_PAGE_DOWN = 34
PWE_KEY_END = 35
PWE_KEY_HOME = 36
PWE_KEY_LEFT = 37
PWE_KEY_UP = 38
PWE_KEY_RIGHT = 39
PWE_KEY_DOWN = 40
PWE_KEY_INSERT = 45
PWE_KEY_DELETE = 46
PWE_KEY_PRINT_SCREEN = 44
PWE_KEY_SCROLL_LOCK = 145
PWE_KEY_PAUSE = 19
PWE_KEY_NUM_LOCK = 144
PWE_KEY_KP_DIVIDE = 111
PWE_KEY_KP_MULTIPLY = 106
PWE_KEY_KP_SUBTRACT = 109
PWE_KEY_KP_ADD = 107
PWE_KEY_KP_ENTER = 13

PWE_EVENTS = [
    PWE_KEY_SPACE,
    PWE_KEY_APOSTROPHE,
    PWE_KEY_COMMA,
    PWE_KEY_MINUS,
    PWE_KEY_PERIOD,
    PWE_KEY_SLASH,
    PWE_KEY_0,
    PWE_KEY_1,
    PWE_KEY_2,
    PWE_KEY_3,
    PWE_KEY_4,
    PWE_KEY_5,
    PWE_KEY_6,
    PWE_KEY_7,
    PWE_KEY_8,
    PWE_KEY_9,
    PWE_KEY_SEMICOLON,
    PWE_KEY_EQUAL,
    PWE_KEY_A,
    PWE_KEY_B,
    PWE_KEY_C,
    PWE_KEY_D,
    PWE_KEY_E,
    PWE_KEY_F,
    PWE_KEY_G,
    PWE_KEY_H,
    PWE_KEY_I,
    PWE_KEY_J,
    PWE_KEY_K,
    PWE_KEY_L,
    PWE_KEY_M,
    PWE_KEY_N,
    PWE_KEY_O,
    PWE_KEY_P,
    PWE_KEY_Q,
    PWE_KEY_R,
    PWE_KEY_S,
    PWE_KEY_T,
    PWE_KEY_U,
    PWE_KEY_V,
    PWE_KEY_W,
    PWE_KEY_X,
    PWE_KEY_Y,
    PWE_KEY_Z,
    PWE_KEY_LEFT_BRACKET,
    PWE_KEY_BACKSLASH,
    PWE_KEY_RIGHT_BRACKET,
    PWE_KEY_GRAVE_ACCENT,
    PWE_KEY_WORLD_1,
    PWE_KEY_WORLD_2,
    PWE_MOUSE_BUTTON_RIGHT,
    PWE_MOUSE_BUTTON_LEFT,
    PWE_MOUSE_BUTTON_MIDDLE,
    PWE_KEY_BACKSPACE,
    PWE_KEY_TAB,
    PWE_KEY_ENTER,
    PWE_KEY_SHIFT,
    PWE_KEY_CONTROL,
    PWE_KEY_ALT,
    PWE_KEY_CAPS_LOCK,
    PWE_KEY_ESC,
    PWE_KEY_PAGE_UP,
    PWE_KEY_PAGE_DOWN,
    PWE_KEY_END,
    PWE_KEY_HOME,
    PWE_KEY_LEFT,
    PWE_KEY_UP,
    PWE_KEY_RIGHT,
    PWE_KEY_DOWN,
    PWE_KEY_INSERT,
    PWE_KEY_DELETE,
    PWE_KEY_PRINT_SCREEN,
    PWE_KEY_SCROLL_LOCK,
    PWE_KEY_PAUSE,
    PWE_KEY_NUM_LOCK,
    PWE_KEY_KP_DIVIDE,
    PWE_KEY_KP_MULTIPLY,
    PWE_KEY_KP_SUBTRACT,
    PWE_KEY_KP_ADD,
    PWE_KEY_KP_ENTER,
]
